// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuRlgc9MXKuWoAkuqKFMJKlLk0TQBPK0c',
    appId: '1:549737506127:web:67bdbb29af5a45a2e7513a',
    messagingSenderId: '549737506127',
    projectId: 'sns-volume2',
    authDomain: 'sns-volume2.firebaseapp.com',
    storageBucket: 'sns-volume2.appspot.com',
    measurementId: 'G-45Z0HLSN4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhNzI1Ka1pgg3TD0k2wv7QHAEXhsF12cg',
    appId: '1:549737506127:android:332e5af93272449ee7513a',
    messagingSenderId: '549737506127',
    projectId: 'sns-volume2',
    storageBucket: 'sns-volume2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkyaOQYkUcKBYZj57KMco5MxgjQJsm1fM',
    appId: '1:549737506127:ios:c3fb13105d1644d1e7513a',
    messagingSenderId: '549737506127',
    projectId: 'sns-volume2',
    storageBucket: 'sns-volume2.appspot.com',
    iosClientId: '549737506127-q7l3io7b5j0qu73gmhe56f7uhi5k96fc.apps.googleusercontent.com',
    iosBundleId: 'com.example.snsVol2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkyaOQYkUcKBYZj57KMco5MxgjQJsm1fM',
    appId: '1:549737506127:ios:c3fb13105d1644d1e7513a',
    messagingSenderId: '549737506127',
    projectId: 'sns-volume2',
    storageBucket: 'sns-volume2.appspot.com',
    iosClientId: '549737506127-q7l3io7b5j0qu73gmhe56f7uhi5k96fc.apps.googleusercontent.com',
    iosBundleId: 'com.example.snsVol2',
  );
}
